import { Location } from './types';

export const LOCATIONS: Location[] = [
  { id: '1', x: 187, y: 328, type: 'company', name: 'Fyto' },
  { id: '2', x: 197, y: 345, type: 'research', name: 'Salk Institute' },
  { id: '3', x: 231, y: 373, type: 'company', name: 'microTERRA' },
  { id: '4', x: 221, y: 286, type: 'research', name: 'Research of prof. Laird at University of Lethbridge' },
  { id: '5', x: 242, y: 354, type: 'company', name: 'Plantible' },
  { id: '6', x: 287, y: 363, type: 'company', name: 'Duckweed Biotech Corp' },
  { id: '7', x: 295, y: 324, type: 'research', name: 'Research of Dr. Sartor on North Carolina State University' },
  { id: '8', x: 250, y: 305, type: 'company', name: 'Lemna Environmental Technologies' },
  { id: '9', x: 283, y: 292, type: 'research', name: 'Collection of Lemna spp. cultures at Canadian Phycological Culture Centre (CPCC)' },
  { id: '10', x: 318, y: 277, type: 'research', name: 'Rutgers Lam Lab' },
  { id: '11', x: 323, y: 302, type: 'company', name: 'Floatmeal' },
  { id: '12', x: 843, y: 303, type: 'company', name: 'Floatmeal' },
  { id: '13', x: 826, y: 333, type: 'research', name: 'Research of Dr. Ishizawa at University of Hyogo' },
  { id: '14', x: 787, y: 364, type: 'research', name: "Wenqin Wang's Lab at Shanghai Normal University" },
  { id: '15', x: 776, y: 327, type: 'research', name: 'Research of Zhao at Chengdu Institute of Biology, Chinese Academy of Sciences' },
  { id: '16', x: 675, y: 393, type: 'company', name: 'Lemnion Green Solutions' },
  { id: '17', x: 694, y: 373, type: 'research', name: 'Research of Dr. Sree on Banaras Hindu University' },
  { id: '18', x: 568, y: 292, type: 'research', name: 'Research of Dr. Borisjuk at Institute of Cell Biology and Genetic Engineering, National Academy of Sciences of Ukraine' },
  { id: '19', x: 575, y: 349, type: 'research', name: 'Gillor Research Group at Zuckerberg Institute for Water Research' },
  { id: '20', x: 582, y: 339, type: 'research', name: 'Weizmann Institute of Science, Department of Plant & Environmental Sciences' },
  { id: '21', x: 583, y: 347, type: 'company', name: 'GreenOnyx' },
  { id: '22', x: 465, y: 267, type: 'research', name: 'Research of prof. Jansen at University College Cork' },
  { id: '23', x: 481, y: 268, type: 'company', name: 'Sustainable Planet' },
  { id: '24', x: 480, y: 272, type: 'research', name: 'Duckweed Research at Nottingham' },
  { id: '25', x: 524, y: 288, type: 'research', name: 'Research of Dr. Marí-Ordóñez at the Gregor Mendel Institute of Molecular Plant Biology (GMI) of the Austrian Academy of Sciences' },
  { id: '26', x: 524, y: 312, type: 'research', name: 'Research of Dr. Morello at the Institute of Agricultural Biology and Biotechnology of National Research Council of Italy' },
  { id: '27', x: 538, y: 291, type: 'research', name: 'Research of Dr. Oláh at University of Debrecen' },
  { id: '28', x: 509, y: 295, type: 'research', name: 'Cryo and Stress research group at the Leibniz Institute of Plant Genetics and Crop Plant Research' },
  { id: '29', x: 514, y: 275, type: 'research', name: 'Research of Dr. Appenroth at Matthias Schleiden Institute, University of Jena' }
];